Repository woocommerce/action-scheduler, pull requests merged in 2018-06, with the labels that each got.

#154 Adding ability to execute actions by group
  classes/ActionScheduler_Store.php
  classes/ActionScheduler_WPCLI_QueueRunner.php
  classes/ActionScheduler_WPCLI_Scheduler_command.php
  classes/ActionScheduler_wpPostStore.php
  tests/phpunit/jobstore/ActionScheduler_wpPostStore_Test.php
Labels: Status: Needs Review, Unit Tests, enhancement

#164 Use `get_allowed_concurrent_batches()` method for WP CLI
  classes/ActionScheduler_WPCLI_QueueRunner.php
Labels: Status: Needs Review

#163 Add max execution time for Siteground
  classes/ActionScheduler_QueueRunner.php
Labels: Status: Needs Review, enhancement

#165 When querying actions ordered by 'group', include joins on term tables
  classes/ActionScheduler_wpPostStore.php
Labels: Status: Needs Review

#162 Implement custom DateTime class
  classes/ActionScheduler_CronSchedule.php
  classes/ActionScheduler_DateTime.php
  classes/ActionScheduler_IntervalSchedule.php
  classes/ActionScheduler_ListTable.php
  classes/ActionScheduler_SimpleSchedule.php
  functions.php
  lib/cron-expression/CronExpression.php
  tests/phpunit/jobstore/ActionScheduler_wpPostStore_Test.php
  tests/phpunit/procedural_api/procedural_api_Test.php
  tests/phpunit/runner/ActionScheduler_QueueRunner_Test.php
  tests/phpunit/schedules/ActionScheduler_IntervalSchedule_Test.php
Labels: Status: Needs Review, Unit Tests

#161 Support hooks filter when staking a claim and add a WP CLI --hooks option to take advantage of it
  README.md
  classes/ActionScheduler_Store.php
  classes/ActionScheduler_WPCLI_QueueRunner.php
  classes/ActionScheduler_WPCLI_Scheduler_command.php
  classes/ActionScheduler_wpPostStore.php
  tests/phpunit/jobstore/ActionScheduler_wpPostStore_Test.php
Labels: Status: Needs Merge, Unit Tests

#167 Fix claim by group or hooks for 2...n queue run via WP CLI command
  classes/ActionScheduler_WPCLI_Scheduler_command.php
Labels: bug
