Repository woocommerce/action-scheduler, pull requests merged in 2018-08, with the labels that each got.

#190 Use var_export() for admin list table args column - fixes Array to string conversion notice
  classes/ActionScheduler_ListTable.php
Labels: Status: Needs Review, bug

#192 Restore batch processing loop
  classes/ActionScheduler_Abstract_QueueRunner.php
  classes/ActionScheduler_Compatibility.php
  classes/ActionScheduler_QueueRunner.php
Labels: Status: Has Feedback

#191 Only process pending actions
  classes/ActionScheduler_Abstract_QueueRunner.php
  classes/ActionScheduler_FatalErrorMonitor.php
  classes/ActionScheduler_Logger.php
  classes/ActionScheduler_wpCommentLogger.php
Labels: Status: Has Feedback, bug

#194 Fix remove_action() calls
  classes/ActionScheduler_FatalErrorMonitor.php
Labels: Housekeeping, Status: Needs Review
