Repository woocommerce/action-scheduler, pull requests merged in 2018-07, with the labels that each got.

#173 2.0.0 Release
  action-scheduler.php
  composer.json
Labels: Housekeeping

#177 Add cautionary note on action dependencies to README
  README.md
Labels: Docs, Status: Has Feedback, Status: Needs Merge

#181 Use as_ prefix not wc_ prefix for public API functions
  README.md
  classes/ActionScheduler.php
  deprecated/functions.php
  functions.php
  tests/phpunit/logging/ActionScheduler_wpCommentLogger_Test.php
  tests/phpunit/procedural_api/procedural_api_Test.php
  tests/phpunit/procedural_api/wc_get_scheduled_actions_Test.php
Labels: enhancement

#183 Don't use wc_clean()
  classes/ActionScheduler_Abstract_ListTable.php
Labels: Status: Needs Review
