Repository woocommerce/action-scheduler, pull requests merged in 2018-05, with the labels that each got.

#132 Don't stop WP CLI execution when claim lost on one batch
  classes/ActionScheduler_WPCLI_QueueRunner.php
Labels: Status: Needs Review

#138 Pass both args to WPCLI_QueueRunner::action_failed()
  classes/ActionScheduler_WPCLI_QueueRunner.php
Labels: bug

#142 Fix incorrect unit test counts
  tests/ActionScheduler_UnitTestCase.php
  tests/phpunit/deprecated/ActionScheduler_UnitTestCase.php
Labels: Status: Needs Review, Unit Tests

#139 Claim actions by oldest ID
  classes/ActionScheduler_wpPostStore.php
  tests/phpunit/jobstore/ActionScheduler_wpPostStore_Test.php
Labels: Status: Has Feedback, enhancement
