Repository woocommerce/action-scheduler, pull requests merged in 2019-07, with the labels that each got.

#299 include actions with no group when sorting actions by group
  classes/ActionScheduler_wpPostStore.php
Labels: Status: Needs Review

#316 add help screen to admin list table
  classes/ActionScheduler.php
  classes/ActionScheduler_AdminHelp.php
Labels: Status: Needs Review

#259 Add database tables
  classes/ActionScheduler_DataController.php
  classes/WP_CLI/ActionScheduler_WPCLI_QueueRunner.php
  classes/WP_CLI/ActionScheduler_WPCLI_Scheduler_command.php
  classes/WP_CLI/Migration_Command.php
  classes/WP_CLI/ProgressBar.php
  classes/abstracts/ActionScheduler.php
  classes/abstracts/ActionScheduler_Abstract_Schema.php
  classes/abstracts/ActionScheduler_Logger.php
  classes/abstracts/ActionScheduler_Store.php
  classes/data-stores/ActionScheduler_DBLogger.php
  classes/data-stores/ActionScheduler_DBStore.php
  classes/data-stores/ActionScheduler_HybridStore.php
  classes/migration/ActionMigrator.php
  classes/migration/ActionScheduler_DBStoreMigrator.php
  classes/migration/BatchFetcher.php
  classes/migration/Config.php
  classes/migration/Controller.php
  classes/migration/DryRun_ActionMigrator.php
  classes/migration/DryRun_LogMigrator.php
  classes/migration/LogMigrator.php
  classes/migration/Runner.php
  classes/migration/Scheduler.php
  classes/schema/ActionScheduler_LoggerSchema.php
  classes/schema/ActionScheduler_StoreSchema.php
  composer.json
  tests/phpunit.xml.dist
  tests/phpunit/jobstore/ActionScheduler_DBStoreMigrator_Test.php
  tests/phpunit/jobstore/ActionScheduler_DBStore_Test.php
  tests/phpunit/jobstore/ActionScheduler_HybridStore_Test.php
  tests/phpunit/jobstore/ActionScheduler_wpPostStore_Test.php
  tests/phpunit/logging/ActionScheduler_DBLogger_Test.php
  tests/phpunit/logging/ActionScheduler_wpCommentLogger_Test.php
  tests/phpunit/migration/ActionMigrator_Test.php
  tests/phpunit/migration/BatchFetcher_Test.php
  tests/phpunit/migration/Config_Test.php
  tests/phpunit/migration/LogMigrator_Test.php
  tests/phpunit/migration/Runner_Test.php
  tests/phpunit/migration/Scheduler_Test.php
Labels: Status: Needs Review, custom-tables, performance

#337 Do not mark action complete in Migration\Scheduler
  classes/migration/Runner.php
  classes/migration/Scheduler.php
Labels: bug
