Repository woocommerce/action-scheduler, pull requests merged in 2020-03, with the labels that each got.

#462 Remove .editorconfig from the export
  .gitattributes
Labels: Housekeeping

#487 restore action handling to WC status, use data store to delete actions
  classes/ActionScheduler_AdminView.php
  classes/abstracts/ActionScheduler_Abstract_ListTable.php
Labels: Status: Has Feedback, Status: Needs Merge

#488 fix initialization order on activation
  classes/abstracts/ActionScheduler.php
Labels: Housekeeping, Status: Needs Merge

#481 update message missed in #329
  classes/abstracts/ActionScheduler_Logger.php
Labels: Status: Needs Merge

#493 add null action check to list table display items
  classes/ActionScheduler_ListTable.php
Labels: Status: Needs Merge, bug

#492 add table missing notice with action link
  classes/ActionScheduler_ListTable.php
  classes/abstracts/ActionScheduler_Abstract_ListTable.php
  classes/abstracts/ActionScheduler_Abstract_Schema.php
Labels: Status: Needs Merge, compatibility, custom-tables, enhancement

#494 Tag version 3.1.3
  action-scheduler.php
  package.json
Labels: Status: Needs Merge

#499 tag version 3.1.4
  action-scheduler.php
  package.json
Labels: Status: Needs Merge

#505 Usage updates for as_unschedule_all_actions()
  docs/api.md
Labels: Docs

#480 Doc clarification. Fixes #479
  docs/usage.md
Labels: Docs
