Repository woocommerce/action-scheduler, pull requests merged in 2020-02, with the labels that each got.

#450 ensure plugin is initialized on activation
  classes/abstracts/ActionScheduler.php
Labels: Status: Needs Review, bug, custom-tables

#451 use correct translation function for numbered string
  classes/ActionScheduler_ListTable.php
Labels: Status: Needs Merge, bug

#452 increase default async runner sleep time to 5 seconds
  classes/ActionScheduler_AsyncRequest_QueueRunner.php
Labels: Status: Needs Merge

#456 Remove the page and search string from status links in list table
  classes/abstracts/ActionScheduler_Abstract_ListTable.php
Labels: Status: Needs Review, bug

#458 unhook async request dispatch after dispatching request
  classes/ActionScheduler_AsyncRequest_QueueRunner.php
  classes/ActionScheduler_QueueRunner.php
Labels: Status: Needs Review, bug

#455 Allow alternate storage engine
  classes/abstracts/ActionScheduler_Store.php
  classes/data-stores/ActionScheduler_DBStore.php
  classes/data-stores/ActionScheduler_wpPostStore.php
  classes/schema/ActionScheduler_LoggerSchema.php
  classes/schema/ActionScheduler_StoreSchema.php
Labels: Status: Needs Review, enhancement

#459 bump version to 3.1.0
  action-scheduler.php
Labels: Housekeeping

#470 Unmark migration when a plugin is deactivated to prevent action loss.
  classes/ActionScheduler_DataController.php
Labels: Status: Needs Review

#472 remove composer autoloading
  action-scheduler.php
  classes/ActionScheduler_wcSystemStatus.php
  classes/abstracts/ActionScheduler.php
  composer.json
  composer.lock
Labels: Status: Needs Review, compatibility

#473 bump version to 3.1.1
  action-scheduler.php
  package.json
Labels: Status: Needs Review
