Repository woocommerce/action-scheduler, pull requests merged in 2020-06, with the labels that each got.

#561 Add new hook to delete_action() method BEFORE action is deleted
  classes/data-stores/ActionScheduler_DBStore.php
Labels: Status: Needs Review

#562 support decimal gmt_offset
  classes/ActionScheduler_DateTime.php
  classes/abstracts/ActionScheduler_TimezoneHelper.php
Labels: Status: Needs Review

#475 Unschedule action only by hook name
  docs/api.md
  functions.php
Labels: status: needs feedback

#567 Improve "Scheduled Date" for async actions
  classes/ActionScheduler_ListTable.php
Labels: Docs

#579 Fix - PHP notice on list table
  classes/abstracts/ActionScheduler_Abstract_ListTable.php
Labels: Status: Needs Review

#572 Fatal Error when WooCommerce is not installed
  classes/ActionScheduler_wcSystemStatus.php
Labels: Status: Needs Review
