Repository woocommerce/action-scheduler, pull requests merged in 2020-01, with the labels that each got.

#409 release version 3.0.0
  action-scheduler.php
  tests/phpunit/procedural_api/procedural_api_Test.php
Labels: Status: Needs Review

#407 update FAQ for 3.0
  docs/faq.md
Labels: Docs, Status: Needs Review

#408 update favicons to WooCommerce favicons
  docs/android-chrome-192x192.png
  docs/android-chrome-256x256.png
  docs/apple-touch-icon.png
  docs/favicon-16x16.png
  docs/favicon-32x32.png
  docs/favicon.ico
Labels: Docs, Status: Needs Review

#415 bump schema and plugin versions
  action-scheduler.php
  classes/abstracts/ActionScheduler_Abstract_Schema.php
  classes/schema/ActionScheduler_LoggerSchema.php
  classes/schema/ActionScheduler_StoreSchema.php
Labels: Status: Needs Review, bug, custom-tables

#414 Update docs for version 3.0
  docs/api.md
  docs/index.md
  docs/perf.md
Labels: Status: Needs Merge

#424 add version 3.0 FAQ
  docs/_layouts/default.html
  docs/version3-0.md
Labels: Docs, Status: Needs Review, custom-tables

#425 update travis configuration with current version matrix
  .travis.yml
Labels: Housekeeping, Status: Needs Review, Unit Tests

#442 add spacing for text domain replacement when used as a composer dependency
  classes/data-stores/ActionScheduler_wpPostStore.php
  classes/data-stores/ActionScheduler_wpPostStore_TaxonomyRegistrar.php
Labels: Housekeeping, Status: Needs Review

#443 add composer autoloading
  action-scheduler.php
  classes/ActionScheduler_AdminView.php
  classes/ActionScheduler_wcSystemStatus.php
  classes/abstracts/ActionScheduler.php
  composer.json
Labels: Status: Needs Review, compatibility

#440 move action_execute hook to after status check
  classes/abstracts/ActionScheduler_Abstract_QueueRunner.php
  classes/abstracts/ActionScheduler_Logger.php
Labels: Status: Needs Review, custom-tables
